# ⛹️‍♀️ College Basketball Dataset ⛹️‍♂️

```
made with ❤️ by Monika Osiak and Jakub Przygodzki

Applied Computer Science, Faculty of Electrical Engineering, Warsaw University of Technology, 2019Z
```

![very-important-meme.png](attachment:very-important-meme.png)

## Informations about dataset

### Variables

1. **TEAM:** The Division I college basketball school **(nazwa zespołu)**

2. **CONF:** The Athletic Conference in which the school participates in **(w której konferencji wystepuje zespół)**
    1. A10 = Atlantic 10, 
    2. ACC = Atlantic Coast Conference, 
    3. AE = America East, 
    4. Amer = American, 
    5. ASun = ASUN, 
    6. B10 = Big Ten, 
    7. B12 = Big 12, 
    8. BE = Big East, 
    9. BSky = Big Sky, 
    10. BSth = Big South, 
    11. BW = Big West, 
    12. CAA = Colonial Athletic Association, 
    13. CUSA = Conference USA, 
    14. Horz = Horizon League, 
    15. Ivy = Ivy League, 
    16. MAAC = Metro Atlantic Athletic Conference, 
    17. MAC = Mid-American Conference, 
    18. MEAC = Mid-Eastern Athletic Conference, 
    19. MVC = Missouri Valley Conference, 
    20. MWC = Mountain West, 
    21. NEC = Northeast Conference, 
    22. OVC = Ohio Valley Conference, 
    23. P12 = Pac-12, 
    24. Pat = Patriot League, 
    25. SB = Sun Belt, 
    26. SC = Southern Conference, 
    27. SEC = South Eastern Conference, 
    28. Slnd = Southland Conference, 
    29. Sum = Summit League, 
    30. SWAC = Southwestern Athletic Conference, 
    31. WAC = Western Athletic Conference, 
    31. WCC = West Coast Conference)

3. **G:** Number of games played **(liczba rozegranych meczów)**

4. **W:** Number of games won **(liczba wygranych meczów)**

5. **ADJOE:** Adjusted Offensive Efficiency (An estimate of the offensive efficiency (points scored per 100 possessions) a team would have against the average Division I defense) **(procentowa skuteczność ataku, którą zespół osiągnąłby przeciwko typowej obronie drużyny z Division I)**

6. **ADJDE:** Adjusted Defensive Efficiency (An estimate of the defensive efficiency (points allowed per 100 possessions) a team would have against the average Division I offense) **(procentowa skuteczność obrony, którą zespół osiągnąłby przeciwko typowemu atakowi drużyny z Division I)**

7. **BARTHAG:** Power Rating (Chance of beating an average Division I team) **(jak silna jest drużyna; szanse na pokonanie typowej drużyny Division I)**

8. **EFG_O:** [Effective Field Goal Percentage](https://en.wikipedia.org/wiki/Effective_field_goal_percentage) Shot **(ile rzutów z gry (2 lub 3 pkt))**

9. **EFG_D:** Effective Field Goal Percentage Allowed

10. **TOR:** Turnover Percentage Allowed (Turnover Rate) **(ile strat piłki)**

11. **TORD:** Turnover Percentage Committed (Steal Rate) **(ile przejęć piłki po stracie przeciwnika)**

12. **ORB:** [Offensive Rebound Percentage](https://en.wikipedia.org/wiki/Rebound_rate) **(ile zbiórek w ataku)**

13. **DRB:** [Defensive Rebound Percentage](https://en.wikipedia.org/wiki/Rebound_rate) **(ile zbiórek w obronie)**

14. **FTR:** Free Throw Rate (How often the given team shoots Free Throws) **(jak często zespół trafia rzuty osobiste (1pkt))**

15. **FTRD:** Free Throw Rate Allowed

16. **2P_O:** Two-Point Shooting Percentage **(rzuty za dwa punkty)**

17. **2P_D:** Two-Point Shooting Percentage Allowed

18. **3P_O:** Three-Point Shooting Percentage **(rzuty za trzy punkty)**

19. **3P_D:** Three-Point Shooting Percentage Allowed

20. **ADJ_T:** Adjusted Tempo (An estimate of the tempo (possessions per 40 minutes) a team would have against the team that wants to play at an average Division I tempo) **(posiadanie piłki, jakie zespół osiągnąłby w starciu z typową drużyną Division I)**

21. **WAB:** Wins Above Bubble (The bubble refers to the cut off between making the NCAA March Madness Tournament and not making it)

22. **POSTSEASON:** Round where the given team was eliminated or where their season ended
    1. R68 = First Four, 
    2. R64 = Round of 64, 
    3. R32 = Round of 32, 
    4. S16 = Sweet Sixteen, 
    5. E8 = Elite Eight, 
    6. F4 = Final Four, 
    7. 2ND = Runner-up, 
    8. Champion = Winner of the NCAA March Madness Tournament for that given year

23. **SEED:** Seed in the NCAA March Madness Tournament

24. **YEAR:** Season

## Exploratory Data Analysis

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
original_data = pd.read_csv('cbb.csv')
original_data.head()

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
0,North Carolina,ACC,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,...,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016
1,Wisconsin,B10,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,...,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015
2,Michigan,B10,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,...,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018
3,Texas Tech,B12,38,31,115.2,85.2,0.9696,53.5,43.0,17.7,...,36.6,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019
4,Gonzaga,WCC,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,...,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017

In [3]:
# how much data do we have?
original_data.shape

(1757, 24)

In [4]:
# what kind of features do we have?
original_data.dtypes

TEAM           object
CONF           object
G               int64
W               int64
ADJOE         float64
ADJDE         float64
BARTHAG       float64
EFG_O         float64
EFG_D         float64
TOR           float64
TORD          float64
ORB           float64
DRB           float64
FTR           float64
FTRD          float64
2P_O          float64
2P_D          float64
3P_O          float64
3P_D          float64
ADJ_T         float64
WAB           float64
POSTSEASON     object
SEED          float64
YEAR            int64
dtype: object

In [5]:
# how much data is missing?
original_data.isnull().sum()

TEAM             0
CONF             0
G                0
W                0
ADJOE            0
ADJDE            0
BARTHAG          0
EFG_O            0
EFG_D            0
TOR              0
TORD             0
ORB              0
DRB              0
FTR              0
FTRD             0
2P_O             0
2P_D             0
3P_O             0
3P_D             0
ADJ_T            0
WAB              0
POSTSEASON    1417
SEED          1417
YEAR             0
dtype: int64

There is no missing data except for two columns: `SEED` and `POSTSEASON`. Actually, these features do not seem to be important for our model so I can remove them.

We do not need also `TEAM`, `CONF` and `YEAR` features so I remove them as well.

I will make one new feature (called `WINS_PERCENT`) out of `G` and `W`. `WINS_PERCENT` feature is going to be the one to be predicted.

In [8]:
data = original_data.drop(['SEED', 'POSTSEASON', 'TEAM', 'CONF', 'YEAR', 'G', 'W'], axis = 1)
data['WINS_PERCENT'] = original_data.W / original_data.G
data

,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,TORD,ORB,DRB,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,WINS_PERCENT
0,123.3,94.9,0.9531,52.6,48.1,15.4,18.2,40.7,30.0,32.3,30.4,53.9,44.6,32.7,36.2,71.7,8.6,0.825000
1,129.1,93.6,0.9758,54.8,47.7,12.4,15.8,32.1,23.7,36.2,22.4,54.8,44.7,36.5,37.5,59.3,11.3,0.900000
2,114.4,90.4,0.9375,53.9,47.7,14.0,19.5,25.5,24.9,30.7,30.0,54.7,46.8,35.2,33.2,65.9,6.9,0.825000
3,115.2,85.2,0.9696,53.5,43.0,17.7,22.8,27.4,28.7,32.9,36.6,52.8,41.9,36.5,29.7,67.5,7.0,0.815789
4,117.8,86.3,0.9728,56.6,41.1,16.2,17.1,30.0,26.2,39.0,26.9,56.3,40.0,38.2,29.0,71.5,7.7,0.948718
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1752,111.2,94.7,0.8640,51.4,46.9,19.2,15.3,33.9,27.3,32.0,27.6,52.5,45.7,32.9,32.6,70.3,1.9,0.628571
1753,117.9,96.6,0.9081,51.2,49.9,17.9,20.1,36.7,30.8,37.1,33.1,52.9,49.4,31.9,33.7,71.2,7.3,0.800000
1754,122.8,95.2,0.9488,55.3,48.1,15.8,18.0,31.6,30.2,33.3,34.9,55.4,44.7,36.7,35.4,68.8,9.9,0.861111
1755,117.4,94.5,0.9238,55.2,44.8,17.1,15.1,32.1,26.0,34.4,28.1,54.3,44.4,37.8,30.3,68.2,2.1,0.771429
1756,117.2,94.9,0.9192,57.0,47.1,16.1,17.4,33.0,23.1,32.1,29.1,58.2,44.1,36.8,35.0,70.5,4.9,0.864865